# DirectAdmin Configuration File
server_name=localhost
port=2222
ssl=1
secure_access_group=directadmin
admin=admin
ns1=ns1.example.com
ns2=ns2.example.com
mysql=1
mysql_host=localhost
mysql_user=da_admin
mysql_pass=changeme
dkim=1
nginx=1
nginx_proxy=1
awstats=1
mail_partition=/var/mail
default_acme_provider=zerossl
password_check_script=scripts/custom/difficult_password.php
enforce_difficult_passwords=0
acme_server_cert_dns_provider=route53
acme_server_cert_enabled=1
