package constants

// DirectAdmin command constants extracted from the original binary
// These represent all the available operations and endpoints in DirectAdmin

const (
	// Account management commands
	CMD_ACCOUNT_ADMIN    = "CMD_ACCOUNT_ADMIN"
	CMD_ACCOUNT_RESELLER = "CMD_ACCOUNT_RESELLER"
	CMD_ACCOUNT_USER     = "CMD_ACCOUNT_USER"
	
	// Admin commands
	CMD_ADMIN_BACKUP_MODIFY  = "CMD_ADMIN_BACKUP_MODIFY"
	CMD_ADMIN_BACKUP_MONITOR = "CMD_ADMIN_BACKUP_MONITOR"
	CMD_ADMIN_CRON_JOBS      = "CMD_ADMIN_CRON_JOBS"
	CMD_ADMIN_FILE_EDITOR    = "CMD_ADMIN_FILE_EDITOR"
	CMD_ADMIN_HISTORY        = "CMD_ADMIN_HISTORY"
	CMD_ADMIN_LIMITS         = "CMD_ADMIN_LIMITS"
	CMD_ADMIN_SSL            = "CMD_ADMIN_SSL"
	CMD_ADMIN_STATS          = "CMD_ADMIN_STATS"
	
	// AJAX commands
	CMD_AJAX_CHECK_DOMAIN   = "CMD_AJAX_CHECK_DOMAIN"
	CMD_AJAX_CHECK_PASSWORD = "CMD_AJAX_CHECK_PASSWORD"
	CMD_AJAX_CHECK_USERNAME = "CMD_AJAX_CHECK_USERNAME"
	CMD_AJAX_GET_COUNTS     = "CMD_AJAX_GET_COUNTS"
	CMD_AJAX_SEARCH         = "CMD_AJAX_SEARCH"
	CMD_AJAX_USERS          = "CMD_AJAX_USERS"
	
	// API commands - Account management
	CMD_API_ACCOUNT_ADMIN    = "CMD_API_ACCOUNT_ADMIN"
	CMD_API_ACCOUNT_RESELLER = "CMD_API_ACCOUNT_RESELLER"
	CMD_API_ACCOUNT_USER     = "CMD_API_ACCOUNT_USER"
	
	// API commands - Admin operations
	CMD_API_ADMIN_BACKUP        = "CMD_API_ADMIN_BACKUP"
	CMD_API_ADMIN_BACKUP_MODIFY = "CMD_API_ADMIN_BACKUP_MODIFY"
	CMD_API_ADMIN_FILE_EDITOR   = "CMD_API_ADMIN_FILE_EDITOR"
	CMD_API_ADMIN_LIMITS        = "CMD_API_ADMIN_LIMITS"
	CMD_API_ADMIN_STATS         = "CMD_API_ADMIN_STATS"
	CMD_API_ADMIN_USAGE         = "CMD_API_ADMIN_USAGE"
	
	// API commands - Domain management
	CMD_API_ADDITIONAL_DOMAINS = "CMD_API_ADDITIONAL_DOMAINS"
	CMD_API_CHANGE_DOMAIN      = "CMD_API_CHANGE_DOMAIN"
	CMD_API_DOMAIN             = "CMD_API_DOMAIN"
	CMD_API_DOMAIN_OWNERS      = "CMD_API_DOMAIN_OWNERS"
	CMD_API_DOMAIN_POINTER     = "CMD_API_DOMAIN_POINTER"
	CMD_API_SHOW_DOMAINS       = "CMD_API_SHOW_DOMAINS"
	CMD_API_SUBDOMAIN          = "CMD_API_SUBDOMAIN"
	
	// API commands - User management
	CMD_API_CHANGE_INFO            = "CMD_API_CHANGE_INFO"
	CMD_API_CHANGE_EMAIL_PASSWORD  = "CMD_API_CHANGE_EMAIL_PASSWORD"
	CMD_API_CHANGE_FTP_PASSWORD    = "CMD_API_CHANGE_FTP_PASSWORD"
	CMD_API_EDIT_USER_MESSAGE      = "CMD_API_EDIT_USER_MESSAGE"
	CMD_API_MODIFY_USER            = "CMD_API_MODIFY_USER"
	CMD_API_SELECT_USERS           = "CMD_API_SELECT_USERS"
	CMD_API_SHOW_USERS             = "CMD_API_SHOW_USERS"
	CMD_API_USER_HISTORY           = "CMD_API_USER_HISTORY"
	CMD_API_USER_PASSWD            = "CMD_API_USER_PASSWD"
	
	// API commands - DNS management
	CMD_API_DNS_CONTROL   = "CMD_API_DNS_CONTROL"
	CMD_API_DNS_MX        = "CMD_API_DNS_MX"
	CMD_API_DNS_RESELLER  = "CMD_API_DNS_RESELLER"
	CMD_API_DNS_ADMIN     = "CMD_API_DNS_ADMIN"
	
	// API commands - Database management
	CMD_API_DATABASES    = "CMD_API_DATABASES"
	CMD_API_DB_USER      = "CMD_API_DB_USER"
	CMD_API_DB_USER_PRIVS = "CMD_API_DB_USER_PRIVS"
	CMD_API_PMA_SIGNON   = "CMD_API_PMA_SIGNON"
	
	// API commands - Email management
	CMD_API_EMAIL_FILTER      = "CMD_API_EMAIL_FILTER"
	CMD_API_EMAIL_FORWARDER   = "CMD_API_EMAIL_FORWARDER"
	CMD_API_EMAIL_POP         = "CMD_API_EMAIL_POP"
	CMD_API_EMAIL_VACATION    = "CMD_API_EMAIL_VACATION"
	CMD_API_SPAMASSASSIN      = "CMD_API_SPAMASSASSIN"
	
	// API commands - File management
	CMD_API_FILE_MANAGER      = "CMD_API_FILE_MANAGER"
	CMD_API_FILE_UPLOAD       = "CMD_API_FILE_UPLOAD"
	CMD_API_FILE_DOWNLOAD     = "CMD_API_FILE_DOWNLOAD"
	CMD_API_FILE_EDITOR       = "CMD_API_FILE_EDITOR"
	
	// API commands - SSL/Security
	CMD_API_SSL                = "CMD_API_SSL"
	CMD_API_SSL_UPLOAD         = "CMD_API_SSL_UPLOAD"
	CMD_API_LETSENCRYPT        = "CMD_API_LETSENCRYPT"
	CMD_API_BRUTE_FORCE_MONITOR = "CMD_API_BRUTE_FORCE_MONITOR"
	CMD_API_LOGIN_KEYS         = "CMD_API_LOGIN_KEYS"
	CMD_API_TWOSTEP_AUTH       = "CMD_API_TWOSTEP_AUTH"
	
	// API commands - Statistics and monitoring
	CMD_API_BANDWIDTH_BREAKDOWN = "CMD_API_BANDWIDTH_BREAKDOWN"
	CMD_API_DU_BREAKDOWN        = "CMD_API_DU_BREAKDOWN"
	CMD_API_LOAD_AVERAGE        = "CMD_API_LOAD_AVERAGE"
	CMD_API_PUBLIC_STATS        = "CMD_API_PUBLIC_STATS"
	CMD_API_SHOW_STATS          = "CMD_API_SHOW_STATS"
	CMD_API_SYSTEM_INFO         = "CMD_API_SYSTEM_INFO"
	
	// API commands - Configuration
	CMD_API_DIRECTADMIN_CONF   = "CMD_API_DIRECTADMIN_CONF"
	CMD_API_CUSTOM_HTTPD       = "CMD_API_CUSTOM_HTTPD"
	CMD_API_MULTI_SERVER       = "CMD_API_MULTI_SERVER"
	CMD_API_PLUGINS            = "CMD_API_PLUGINS"
	CMD_API_PERL_MODULES       = "CMD_API_PERL_MODULES"
	
	// API commands - Backup and restore
	CMD_API_BACKUP_RESTORE     = "CMD_API_BACKUP_RESTORE"
	CMD_API_SITE_BACKUP        = "CMD_API_SITE_BACKUP"
	CMD_API_RESELLER_BACKUP    = "CMD_API_RESELLER_BACKUP"
	
	// API commands - Task queue
	CMD_API_TASKQ              = "CMD_API_TASKQ"
	CMD_API_TASK_QUEUE         = "CMD_API_TASK_QUEUE"
	
	// API commands - Cron jobs
	CMD_API_CRON_JOBS          = "CMD_API_CRON_JOBS"
	
	// API commands - FTP
	CMD_API_FTP_SETTINGS       = "CMD_API_FTP_SETTINGS"
	CMD_API_FTP_SHOW_USERS     = "CMD_API_FTP_SHOW_USERS"
	
	// API commands - Reseller operations
	CMD_API_RESELLER_STATS     = "CMD_API_RESELLER_STATS"
	CMD_API_SHOW_RESELLERS     = "CMD_API_SHOW_RESELLERS"
	CMD_API_PACKAGES           = "CMD_API_PACKAGES"
	
	// API commands - Miscellaneous
	CMD_API_COMMENTS           = "CMD_API_COMMENTS"
	CMD_API_OWNERS_OWNER       = "CMD_API_OWNERS_OWNER"
	CMD_API_RESEND_EMAIL       = "CMD_API_RESEND_EMAIL"
	CMD_API_TICKET             = "CMD_API_TICKET"
	
	// Login and authentication
	CMD_LOGIN                  = "CMD_LOGIN"
	CMD_LOGIN_KEYS             = "CMD_LOGIN_KEYS"
	CMD_LOGIN_KEY_CREATE       = "CMD_LOGIN_KEY_CREATE"
	CMD_LOGIN_KEY_MODIFY       = "CMD_LOGIN_KEY_MODIFY"
	CMD_API_LOGIN_KEY          = "CMD_API_LOGIN_KEY"
	
	// User panel commands
	CMD_DOMAIN                 = "CMD_DOMAIN"
	CMD_SUBDOMAIN              = "CMD_SUBDOMAIN"
	CMD_EMAIL                  = "CMD_EMAIL"
	CMD_FILE_MANAGER           = "CMD_FILE_MANAGER"
	CMD_DB                     = "CMD_DB"
	CMD_SSL                    = "CMD_SSL"
	CMD_CRON_JOBS              = "CMD_CRON_JOBS"
	CMD_CHANGE_PASSWORD        = "CMD_CHANGE_PASSWORD"
	CMD_SITE_BACKUP            = "CMD_SITE_BACKUP"
	CMD_SITE_RESTORE           = "CMD_SITE_RESTORE"
	
	// Reseller panel commands
	CMD_RESELLER_HISTORY       = "CMD_RESELLER_HISTORY"
	CMD_RESELLER_STATS         = "CMD_RESELLER_STATS"
	CMD_SHOW_RESELLERS         = "CMD_SHOW_RESELLERS"
	CMD_SHOW_RESELLER          = "CMD_SHOW_RESELLER"
	CMD_PLUGINS_RESELLER       = "CMD_PLUGINS_RESELLER"
	
	// System commands
	CMD_SERVERSTATUS           = "CMD_SERVERSTATUS"
	CMD_SYSTEM_INFO            = "CMD_SYSTEM_INFO"
	CMD_SERVICES_MONITOR       = "CMD_SERVICES_MONITOR"
	CMD_PROCESSES              = "CMD_PROCESSES"
	
	// Additional domain commands
	CMD_ADDITIONAL_DOMAINS     = "CMD_ADDITIONAL_DOMAINS"
	CMD_ADDITIONAL_DOMAINS_VIEW = "CMD_ADDITIONAL_DOMAINS_VIEW"
	
	// More specialized commands found in binary
	CMD_LETSENCRYPT            = "CMD_LETSENCRYPT"
	CMD_NGINX_UNIT             = "CMD_NGINX_UNIT"
	CMD_PHPMYADMIN             = "CMD_PHPMYADMIN"
	CMD_ROUNDCUBE              = "CMD_ROUNDCUBE"
	CMD_SQUIRRELMAIL           = "CMD_SQUIRRELMAIL"
	CMD_WEBMAIL                = "CMD_WEBMAIL"
	
	// Maintenance and updates
	CMD_UPDATE                 = "CMD_UPDATE"
	CMD_CUSTOMBUILD            = "CMD_CUSTOMBUILD"
	CMD_LICENSE                = "CMD_LICENSE"
	CMD_MAINTENANCE            = "CMD_MAINTENANCE"
)

// Command groups for organization
var AdminCommands = []string{
	CMD_ADMIN_BACKUP_MODIFY,
	CMD_ADMIN_BACKUP_MONITOR,
	CMD_ADMIN_CRON_JOBS,
	CMD_ADMIN_FILE_EDITOR,
	CMD_ADMIN_HISTORY,
	CMD_ADMIN_LIMITS,
	CMD_ADMIN_SSL,
	CMD_ADMIN_STATS,
}

var APICommands = []string{
	CMD_API_ACCOUNT_ADMIN,
	CMD_API_ACCOUNT_RESELLER,
	CMD_API_ACCOUNT_USER,
	CMD_API_SHOW_USERS,
	CMD_API_SHOW_DOMAINS,
	CMD_API_SHOW_RESELLERS,
	CMD_API_MODIFY_USER,
	CMD_API_SELECT_USERS,
	CMD_API_DOMAIN,
	CMD_API_SUBDOMAIN,
	CMD_API_EMAIL_POP,
	CMD_API_DATABASES,
	CMD_API_SSL,
	CMD_API_FILE_MANAGER,
	CMD_API_BACKUP_RESTORE,
	CMD_API_ADMIN_STATS,
	CMD_API_SYSTEM_INFO,
}

var UserCommands = []string{
	CMD_DOMAIN,
	CMD_SUBDOMAIN,
	CMD_EMAIL,
	CMD_FILE_MANAGER,
	CMD_DB,
	CMD_SSL,
	CMD_CRON_JOBS,
	CMD_CHANGE_PASSWORD,
	CMD_SITE_BACKUP,
	CMD_SITE_RESTORE,
}

var ResellerCommands = []string{
	CMD_RESELLER_HISTORY,
	CMD_RESELLER_STATS,
	CMD_SHOW_RESELLERS,
	CMD_SHOW_RESELLER,
	CMD_PLUGINS_RESELLER,
}

// HTTP method mappings for commands
var CommandHTTPMethods = map[string][]string{
	CMD_LOGIN:              {"GET", "POST"},
	CMD_API_LOGIN_KEY:      {"GET", "POST"},
	CMD_API_SHOW_USERS:     {"GET"},
	CMD_API_SHOW_DOMAINS:   {"GET"},
	CMD_API_SHOW_RESELLERS: {"GET"},
	CMD_API_MODIFY_USER:    {"POST"},
	CMD_API_SELECT_USERS:   {"POST"},
	CMD_API_DOMAIN:         {"GET", "POST"},
	CMD_API_SUBDOMAIN:      {"GET", "POST"},
	CMD_API_EMAIL_POP:      {"GET", "POST"},
	CMD_API_DATABASES:      {"GET", "POST"},
	CMD_API_SSL:            {"GET", "POST"},
	CMD_API_FILE_MANAGER:   {"GET", "POST"},
	CMD_API_BACKUP_RESTORE: {"GET", "POST"},
	CMD_API_ADMIN_STATS:    {"GET"},
	CMD_API_SYSTEM_INFO:    {"GET"},
}