# Global PHP handler by extension for litespeed
# Handling .php works even without this, but we add more extensions
<IfModule Litespeed>
<FilesMatch "\.(inc|php|php5|phtml)$">
	AddHandler application/x-httpd-lsphp .inc .php .php5 .phtml
</FilesMatch>
</IfModule>

# Global PHP handler by extension for apache+lsapi
<IfModule mod_lsapi.c>
<FilesMatch "\.(inc|php|php5|phtml)$">
	AddHandler application/x-httpd-lsphp .inc .php .php5 .phtml
</FilesMatch>
</IfModule>
