ServerName		"ProFTPd"
ServerType          	standalone

Port			21
PassivePorts		35000 35999
UseReverseDNS		off
TimesGMT		off
TimeoutLogin		120
TimeoutIdle		600
TimeoutNoTransfer	900
TimeoutStalled		3600

<IfModule mod_tls.c>
	TLSEngine on
	TLSLog /var/log/proftpd/proftpd.tls.log
	TLSProtocol TLSv1 TLSv1.1 TLSv1.2
	TLSCipherSuite HIGH:MEDIUM:+TLSv1
	TLSVerifyClient off
	TLSRequired off
	
	#Certificates
	TLSRSACertificateFile /etc/exim.cert
	TLSRSACertificateKeyFile /etc/exim.key
</IfModule>
<IfModule mod_sftp.c>
	<VirtualHost 0.0.0.0>
		# The SFTP configuration, requires configure.proftpd change to include mod_sftp in with-modules list
		Port 23

		AuthUserFile    /etc/proftpd.passwd
		TransferLog      /var/log/proftpd/xferlog.legacy
		ExtendedLog     /var/log/proftpd/|IP|.bytes WRITE,READ userlog    

		SFTPEngine on

		SFTPLog /var/log/proftpd/sftp.log
		SFTPHostKey /etc/ssh/ssh_host_rsa_key
		SFTPAuthorizedUserKeys file:~/.sftp/authorized_keys

		SFTPClientMatch ".*WS_FTP.*" channelWindowSize 1GB    #WS_FTP initial window size
		SFTPClientMatch ".*ClientSftp" sftpProtocolVersion 3  #CuteFTPPro8
		SFTPClientMatch ".*WinSCP.*" sftpProtocolVersion 3    #upload/download fix for WinSCP
		SFTPClientMatch ".*SecureBlackbox.*" sftpProtocolVersion 3
		SFTPClientMatch "1.0" sftpProtocolVersion 3 channelWindowSize 1GB
		SFTPClientMatch ".*J2SSH_Maverick.*" channelWindowSize 1GB
		SFTPClientMatch ".*WeOnlyDo.*" sftpProtocolVersion 3 channelWindowSize 1GB
		SFTPClientMatch ".*EldoS.SSHBlackbox.3.*" sftpProtocolVersion 3 channelWindowSize 1GB
		SFTPClientMatch ".*IP.Works.*" channelWindowSize 1GB
	</VirtualHost>
</IfModule>

ScoreboardFile  /run/proftpd/proftpd.scoreboard

TransferLog		/var/log/proftpd/xferlog.legacy
LogFormat		default "%h %l %u %t \"%r\" %s %b"
LogFormat		auth    "%v [%P] %h %t \"%r\" %s"
LogFormat		write   "%h %l %u %t \"%r\" %s %b"

#DON'T modify this log format.  Its used by DirectAdmin to determine user usage
LogFormat		userlog "%u %b %m %a"
ExtendedLog		/var/log/proftpd/|IP|.bytes WRITE,READ userlog

AuthUserFile                    /etc/proftpd.passwd
DefaultServer		on
AuthOrder mod_auth_file.c

#AuthPAM off

<Global>
	PassivePorts            35000 35999
	DeferWelcome		on

	RequireValidShell	no

	DefaultRoot		~
	DirFakeUser on ftp
	DirFakeGroup on ftp

	User			ftp
	Group			ftp
	#UserAlias		anonymous ftp

	AllowStoreRestart	on
	AllowRetrieveRestart	on

	ListOptions		-a
	ShowSymlinks		on
	<IfModule mod_facts.c>
		##Enable this with proftpd 1.3.4b+ to fix FileZilla MLSD
		##http://www.proftpd.org/docs/modules/mod_facts.html#FactsOptions
		# FactsOptions UseSlink
	</IfModule>

	Umask			022
	DisplayLogin		welcome.msg
	DisplayChdir		readme
	AllowOverwrite		yes
	ExtendedLog		/var/log/proftpd/access.log WRITE,READ write
	ExtendedLog		/var/log/proftpd/auth.log AUTH auth
	#
	# Paranoia logging level....
	#
	#ExtendedLog    /var/log/proftpd/paranoid.log ALL default
</Global>

<IfModule mod_clamav.c>
	ClamAV on
	ClamStream true
	ClamServer 127.0.0.1
	ClamPort 3310
	ClamMaxSize 5 Mb
</IfModule>
