#0.7

dovecot_config_version = 2.4.0
dovecot_storage_version = 2.4.0

!include conf/ip.conf
!include conf/general.conf
!include conf/limits.conf
!include conf/namespace_private.conf
!include conf/maildir_copy_with_hardlinks.conf
!include conf/custom_passdb.conf
!include conf/passdb.conf
!include conf/alternate_passwd.conf
!include conf/protocols.conf
!include conf/mail_plugins.conf
!include conf/service.conf
!include conf/ssl.conf
!include conf/userdb.conf
!include conf/protocol.conf
!include conf/mail_max_userip_connections.conf
!include conf/lmtp.conf

!include conf.d/*.conf
