#VERSION=0.1
passdb da_alternate {
  passdb_username_filter = *@*
  passwd_file_path=/etc/virtual/%{user | domain}/passwd_alt
  passdb_default_password_scheme=CRYPT
  auth_username_format=%{user | username}
  passdb_driver = passwd-file
}
