auth_username_chars = abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.-_@&
auth_verbose = yes
auth_allow_weak_schemes = yes
login_greeting = Dovecot DA ready.
mail_access_groups = mail
default_login_user = dovecot
mail_path = ~/Maildir
mail_driver = maildir
verbose_proctitle = yes
