passdb unix_user {
  passdb_username_filter = !*@*
  passdb_driver = pam
}

passdb virtual_user {
  passdb_username_filter = *@*
  passwd_file_path=/etc/virtual/%{user | domain}/passwd
  passdb_default_password_scheme=CRYPT
  auth_username_format=%{user | username}
  passdb_driver = passwd-file
}
