protocol imap {
  !include imap_mail_plugins.conf
}

protocol pop3 {
  pop3_uidl_format = %{uid | hex(8)}%{uidvalidity | hex(8)}
  pop3_logout_format = top=%{top_count}/%{top_bytes}, retr=%{retr_count}/%{retr_bytes}, del=%{deleted_count}/%{message_count}, size=%{message_bytes}, bytes=%{input}/%{output}
}
