userdb unix_user {
  # hide "unknown user"
  auth_verbose = no
  userdb_driver = passwd
}

userdb virtual_user {
  passwd_file_path=/etc/virtual/%{user | domain}/passwd
  auth_username_format=%{user | username}
  userdb_driver = passwd-file
  fields {
    # compatibility mode with 2.3 quota rules
    quota_storage_size:default=%{passwd_file:quota_rule|default("*:bytes=0")|substr(8)}
  }
}
